### ISSUE TITLE
[BUG] unable to change recents provider in lawnchair 14 beta 2

### ISSUE THREAD

**Issue by Subhashis2007** [skittles9823/QuickSwitch#55]
[quickswitch-logs_4.0.2.zip](https://github.com/skittles9823/QuickSwitch/files/14881215/quickswitch-logs_4.0.2.zip)
[quickswitch-logs_3.3.0.zip](https://github.com/skittles9823/QuickSwitch/files/14881217/quickswitch-logs_3.3.0.zip)

My OS: lineageOS 21 QPR2

**Comment by Lelonio** [comment]
Same here

**Comment by ironveil** [comment]
Is this the "overlay not created!" error?

If so then I also have this (Pixel 7, LineageOS 21 QPR2). If it helps, it's a QPR2 issue as the previous build (2024-03-15) works fine (with 3.3.8) but this build (2024-04-19) doesn't.

**Comment by rubyowo** [comment]
Same issue with crDroid 10.4 (to be expected)

**Comment by MCcoolman** [comment]
Same Problem on Pixel rom

**Comment by FurhadTheNerd** [comment]
same problem on my pixel 6 running "14 (AP2A.240605.024)" stock with magisk 27

**Comment by wizpizz** [comment]
Will this be fixed at some point? Same issue on Xioami 12S Ultra running LineageOS 21 (14 (AP2A.240705.005))

**Comment by Encampeded** [comment]
Same issue, though on Android 15 with the latest Lawnchair Nightly on a Pixel 7 Pro w/ Android 15 (AP3A.241105.007)

**Comment by Teemuuu** [comment]
Still an issue. Latest Lawnchair Nightly on Pixel 9 Pro, Android 15.
